---
- name: backup cisco switch configuration into daily file
  hosts: cisco_switch
  gather_facts: no
  connection: local
  vars:
    backup_dir: ./backup
  tasks:
  - name: save running config to device
    ios_config:
      save_when: always
      provider: "{{ creds }}"
  - name: get cisco switch config
    ios_command:
      commands: 
      - show running-config
      provider: "{{ creds }}"
    register: config
  - name: ensure backup folder is created
    file:
      path: "{{ backup_dir }}/"
      state: directory
    run_once: yes
  - name: get timestamp
    command: date +%Y%m%d
    register: timestamp
    run_once: yes
  - name: save output to {{ backup_root }} 
    copy: 
      content: "{{ config.stdout[0] }}"
      dest: "{{ backup_dir }}/show_run_{{ inventory_hostname }}_{{ timestamp.stdout }}.txt"
  - name: get device config
    ios_command:
      commands:
      - show vlan brief
      - show interface status
      - show ip arp
      - show cdp neighbors
      - show version
      provider: "{{ creds }}"
    register: config
  - name: save output to {{ backup_root }}
    copy:
      content: |
        {{ config.stdout[0] }}
        ----------------------
        {{ config.stdout[1] }}
        ----------------------
        {{ config.stdout[2] }}
        ----------------------
        {{ config.stdout[3] }}
        ----------------------
        {{ config.stdout[4] }}
      dest: "{{ backup_dir }}/doku_{{ inventory_hostname }}_{{ timestamp.stdout }}.txt"
...
