---
- name: backup cisco switch configuration into daily file
  hosts: cisco_switch
  gather_facts: no
  connection: network_cli
  become: yes
  vars:
    backup_dir: ./backup
  tasks:
  - name: save running config to device
    cisco.ios.ios_config:
      save_when: always
  - name: get cisco switch config
    cisco.ios.ios_command:
      commands: 
      - show running-config
    register: config
  - name: ensure backup folder is created
    ansible.builtin.file:
      path: "{{ backup_dir }}/"
      state: directory
    run_once: yes
    delegate_to: localhost
  - name: get timestamp
    ansible.builtin.command: date +%Y%m%d
    register: timestamp
    run_once: yes
    delegate_to: localhost
  - name: save output to {{ backup_root }} 
    ansible.builtin.copy: 
      content: "{{ config.stdout[0] }}"
      dest: "{{ backup_dir }}/show_run_{{ inventory_hostname }}_{{ timestamp.stdout }}.txt"
    delegate_to: localhost
  - name: get device config
    cisco.ios.ios_command:
      commands:
      - show vlan brief
      - show interface status
      - show ip arp
      - show cdp neighbors
      - show version
    register: config
  - name: save output to {{ backup_root }}
    ansible.builtin.copy:
      content: |
        {{ config.stdout[0] }}
        ----------------------
        {{ config.stdout[1] }}
        ----------------------
        {{ config.stdout[2] }}
        ----------------------
        {{ config.stdout[3] }}
        ----------------------
        {{ config.stdout[4] }}
      dest: "{{ backup_dir }}/doku_{{ inventory_hostname }}_{{ timestamp.stdout }}.txt"
    delegate_to: localhost
...
