#!/usr/bin/env ansible-playbook 
---
- name: Revert ESXi VM back to snapshot and powerOn with Prompt
  hosts: localhost
  vars:
    esxi_host: esxi1
  tasks:
  - name: loop virtual machines
    block:
      - set_fact:
          all_guest_names: []
      - name: Get virtual machine names
        vmware_vm_info:
          hostname: "{{ esxi_host }}"
          username: "{{ esxi_user }}"
          password: "{{ esxi_password }}"
          folder: ""
          validate_certs: no
        delegate_to: localhost
        register: vm_info
      - set_fact:
          all_guest_names: "{{ all_guest_names + [ item.guest_name ] }}"
        no_log: true
        with_items:
          - "{{ vm_info.virtual_machines | json_query(query) }}"
        vars:
          query: "[?guest_name]"

  - name: print all virtual machine names
    debug:
      msg: "{{ all_guest_names }}"

  - pause:
      prompt: "Name of VM"
      echo: yes
    register: vmname_input
  - set_fact:
      vmname: "{{ vmname_input.user_input }}"
  - name: Get VM Snapshots
    vmware_guest_snapshot_info:
      hostname: "{{ esxi_host }}"
      username: "{{ esxi_user }}"
      password: "{{ esxi_password }}"
      datacenter: ""
      folder: ""
      validate_certs: no
      name: "{{ vmname }}"
    register: snapshot_info
    delegate_to: localhost
  - debug: var=snapshot_info.guest_snapshots.snapshots
  - pause:
      prompt: "Snapshot name to revert into"
      echo: yes
    register: snapname_input
  - set_fact:
      snapname: "{{ snapname_input.user_input }}"
  - name: Revert Snapshot
    vmware_guest_snapshot:
      hostname: "{{ esxi_host }}"
      username: "{{ esxi_user }}"
      password: "{{ esxi_password }}"
      datacenter: ""
      folder: ""
      validate_certs: no
      name: "{{ vmname }}"
      state: revert
      snapshot_name: "{{ snapname }}"
      quiesce: yes
      memory_dump: yes
    delegate_to: localhost
  - name: Power on VM
    vmware_guest_powerstate:
      hostname: "{{ esxi_host }}"
      username: "{{ esxi_user }}"
      password: "{{ esxi_password }}"
      validate_certs: no
      name: "{{ vmname }}"
      state: powered-on
    delegate_to: localhost

