- name: clone linked VM in vCenter
  hosts: localhost
  vars:
    vcenter_host: vcenter01
    vcenter_user: administrator@vsphere.local
    vcenter_password: change.ME...
    template: ALPINE
    datacenter: OFFICE
    cluster: LNX
    vmfolder: /Ansible
    network: DMZ
    snapname: snap1
    machines:
      linkclone1:
        cpu: 1
        mem: 256
      linkclone2:
        cpu: 2
        mem: 512
    
  tasks:
    - name: Create a VM from Template
      vmware_guest:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        folder: "{{ vmfolder }}"
        state: poweredoff
        template: "{{ template }}"
        linked_clone: true
        snapshot_src: "{{ snapname }}"
        name: "{{ item.key }}"
        hardware:
          memory_mb: "{{ item.value.mem }}"
          num_cpus: "{{ item.value.cpu }}"
          scsi: paravirtual
        networks:
        - name: "{{ network }}"
        wait_for_ip_address: no
      delegate_to: localhost
      ignore_errors: true
      with_dict: "{{ machines }}"
...
