- name: clone VM in vCenter
  hosts: localhost
  vars:
    vcenter_host: vcenter01
    vcenter_user: administrator@vsphere.local
    vcenter_password: change.ME...
    template: ALPINE
    datacenter: OFFICE
    cluster: LNX
    vmfolder: /Ansible
    network: "DMZ"
    clone_name: fullclone1
    clone_cpu: 1
    clone_mem: 256
    
  tasks:
    - name: Create a VM from Template
      vmware_guest:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        folder: "{{ vmfolder }}"
        state: poweredoff
        template: "{{ template }}"
        name: "{{ clone_name }}"
        hardware:
          memory_mb: "{{ clone_mem }}"
          num_cpus: "{{ clone_cpu }}"
          scsi: paravirtual
        networks:
        - name: "{{ network }}"
        wait_for_ip_address: no
      delegate_to: localhost
      ignore_errors: true
...
