- name: clone linked VM in vCenter
  hosts: localhost
  vars:
    vcenter_host: vcenter01
    vcenter_user: administrator@vsphere.local
    vcenter_password: H0ireka???
    template: ALPINE
    datacenter: OFFICE
    cluster: LNX
    vmfolder: /Ansible
    network: "DMZ"
    snapname: snap1
    clone_name: linkclone1
    clone_cpu: 1
    clone_mem: 256
    
  tasks:
    - name: Create a linked Clone VM from Template
      vmware_guest:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        folder: "{{ vmfolder }}"
        state: poweredoff
        template: "{{ template }}"
        linked_clone: true
        name: "{{ clone_name }}"
        snapshot_src: "{{ snapname }}"
        hardware:
          memory_mb: "{{ clone_mem }}"
          num_cpus: "{{ clone_cpu }}"
          scsi: paravirtual
        networks:
        - name: "{{ network }}"
        wait_for_ip_address: no
      delegate_to: localhost
      ignore_errors: true
...
