---
- name: Update with Important Windows Patches
  hosts: win_hosts
  tasks:
  - name: Apply Patches
    win_updates:
      category_name:
      - SecurityUpdates
      - CriticalUpdates
      blacklist:
      - Windows Malicious Software Removal Tool for Windows
      - \d{4}-\d{2} Cumulative Update for Windows Server 2016
      reboot: yes
      reboot_timeout: 1800
    until: not result.changed
    retries: 10
    delay: 5
    register: update_results

  - name: print update results
    debug:
      var: update_results
...
