---
# tasks file for demo.ping

- name: ping linux host
  ansible.builtin.ping:
  when: ansible_system == "Linux"

- name: ping windows host
  ansible.windows.win_ping:
  when: ansible_system == "Win32NT"

...
